export default {
    GET_CURRENT_LOCATION: "GET_CURRENT_LOCATION",
    UPDATE_DRIVER_STATUS: "UPDATE_DRIVER_STATUS",
    SAVE_DRIVER_PROFILE: "SAVE_DRIVER_PROFILE",
    SHOW_BOOKING_MODAL: "SHOW_BOOKING_MODAL",
    UPDATE_BOOKING_STATUS: "UPDATE_BOOKING_STATUS",
    UPDATE_BOOKING_LOADER: "UPDATE_BOOKING_LOADER",
    GET_BOOKINGS: "GET_BOOKINGS",
    BOOKING_APPROVED: "BOOKING_APPROVED",
    BOOKING_REJECTED: "BOOKING_REJECTED",
    LOGOUT: "LOGOUT"
};